title: ICLR 2024 Workshop on AI4DifferentialEquations in Science
description: ""

timezone: Central European Standard Time

theme: jekyll-theme-minimal #pages-themes/cayman@v0.2.0

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  # Challenge: "https://github.com/geomstats/challenge-iclr-2022"
  # Accepted Papers: "/papers"
  Speakers: "/speakers"
  Organizers: "/organizers"
  Schedule: "/schedule"
  # Past Events: "/past"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
