title: ICLR Workshop on AI
description: ""

timezone: Central European Standard Time

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  # Challenge: "https://github.com/geomstats/challenge-iclr-2022"
  # Accepted Papers: "/papers"
  Speakers: "/speakers"
  Schedule: "/schedule"
  Organizers: "/organizers"
  # Past Events: "/past"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
